version: '3.7'

services:
  szbd:
    restart: always
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=psiDatabase

        #  frontend:
        #    build: ./PSI-App/frontend
        #    image: psi-frontend:1.0
        #    container_name: psi-front
        #    command: ng serve --host=0.0.0.0
        #    environment:
        #      - DEBUG=0
        #    ports:
        #      - '80:4200'
        #    volumes:
        #      - ./PSI-App/frontend:/PSI-App

  frontend:
    image: nginx:latest
    container_name: psi-front
    ports:
        - '9155:80'
    volumes:
        - ./frontend:/usr/share/nginx/html
          # - ./PSI-App/frontend/dist/frontend:/usr/share/nginx/html

  backend:
    build: ./PSI-2020/PSI-2020-backend
    image: psi-backend:1.0
    container_name: psi-backend
    command: sh -c "dotnet-ef database update; dotnet publish -c Release; chmod 777 bin/Release/netcoreapp3.1/PSI-2020-backend; ./bin/Release/netcoreapp3.1/PSI-2020-backend"
    ports:
        - '10521:80'
    environment:
      - ASPNETCORE_URLS=https://+;http://+;
    volumes:
        - ./PSI-2020/PSI-2020-backend/PSI-2020-backend:/PSI-Backend

  backend-auth:
    build: ./PSI-2020/PSI-2020-backend
    image: psi-backend:1.0
    container_name: psi-auth
    command: sh -c "dotnet publish -c Release; chmod 777 bin/Release/netcoreapp3.1/PSI-2020-authentication-mock; ./bin/Release/netcoreapp3.1/PSI-2020-authentication-mock"
    environment:
      - ASPNETCORE_URLS=https://+;http://+;
    volumes:
        - ./PSI-2020/PSI-2020-backend/PSI-2020-authentication-mock:/PSI-Backend

  backend-storage:
    build: ./PSI-2020/PSI-2020-backend
    image: psi-backend:1.0
    container_name: psi-storage
    command: sh -c "dotnet publish -c Release; chmod 777 bin/Release/netcoreapp3.1/PSI-2020-storage-mock; ./bin/Release/netcoreapp3.1/PSI-2020-storage-mock"
    environment:
      - ASPNETCORE_URLS=https://+;http://+;
    volumes:
        - ./PSI-2020/PSI-2020-backend/PSI-2020-storage-mock:/PSI-Backend
